http:
  port: "8081"
  
https:
  port: "8083"
  
anypoint:
  platform:
    login-url: "https://anypoint.mulesoft.com/accounts/api/v2/oauth2/token"
  connectedapp:
    client-id: "a8ffdfe116af47f08db6c7a8ff9673e4"
    client-secret: "7845673a7C594B21bF0d28B817978Dcd"
  apm:
   url-prefix: "https://anypoint.mulesoft.com/partnermanager"
   orgid: "43b555db-2264-4ed5-9c81-d456ba81aaa7"
   envid: "e8c50b0b-cfb9-4635-972e-018b67ea5ea1"
